on:
  workflow_dispatch:
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  schedule:
    # 4a EDT (in UTC) for waiver run
    - cron: '0 8 * 9-12,1-2 0-6'
    # 12p EDT TUE for week final scores
    - cron: '0 16 * 9-12,1-2 2'

name: Quarto Publish

permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Select R Version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv' # The R version to download (if necessary) and use.
          
      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
          
      - name: Load Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # add path per https://stackoverflow.com/questions/78727508/quarto-and-github-actions-error-the-specified-path-is-not-a-website
          # see also https://github.com/quarto-dev/quarto-actions/issues/113
          path: index.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}