on:
  workflow_dispatch:
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  schedule:
    # COMMENT OUT TO GOTO MANUAL FOR END-OF-YEAR ELIMINATOR AND LTS BOWL  
    # 11.30a EDT TUE (in UTC) for SUN & MON 8p gamescore updates and final stat corrections
    - cron: '30 15 * 9-12,1-2 2'
    
    
name: Update Scores

permissions:
    contents: read, write
    pages: read, write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Select R Version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv' 
          
      - name: Load Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1      
          
      - name: Run Score Updates
        shell: Rscript {0}
        run: source("R/get_scores.R")

      - name: Save Score CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save new score file
          branch: main
          commit_options: '--no-verify --signoff'